// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://apwgaqoczdhfqfztnfka.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFwd2dhcW9jemRoZnFmenRuZmthIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyNDU4NDgsImV4cCI6MjA2NTgyMTg0OH0.D-Ul-9y9uV48a5kloC1lyjAUSyJ-G4_5u0LL0uIFYOU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);